rango/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('show_category/<category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('restricted/', views.restricted, name='restricted'),
    path('admin/', admin.site.urls),
]

tango_with_django_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import settings

from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^rango/', include('rango.urls', namespace='rango')),
    # path('admin/', admin.site.urls),
    path('admin/', views.admin),
    path('admin/rango/page/', views.page),
    path('admin/rango/userprofile/', views.userprofile),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.files import ImageFile
from django.db.models.fields.related import OneToOneField
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, primary_key=True)
    views = models.IntegerField(default=1)
    likes = models.IntegerField(default=1)
    slug = models.CharField(max_length=256, default='')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField(max_length=128)
    views = models.IntegerField(default=1)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.fields.related.OneToOneField(User, on_delete=models.CASCADE, default=None)
    website = models.fields.URLField(default='')
    picture = models.fields.files.ImageField(default='')

rango/forms.py
import django.forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import Category, Page, UserProfile


class CategoryForm(ModelForm):

    slug = django.forms.CharField(required=False)

    class Meta:
        model = Category
        fields = ['name', 'views', 'likes', 'slug']


class PageForm(ModelForm):
    title = django.forms.CharField(required=False)
    url = django.forms.URLField(required=False)
    views = django.forms.IntegerField(required=False)

    class Meta:
        model = Page
        fields = ['title', 'url', 'views']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserProfileForm(ModelForm):
    website = django.forms.URLField(required=False)
    picture = django.forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ['website', 'picture']

rango/views.py
from datetime import datetime, timedelta

import requests
from django.contrib import auth
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import CategoryForm, PageForm, UserForm, UserProfileForm
from .models import Category, Page


def index(request):
    if 'visits' not in request.session:
        request.session['visits'] = 0
    if 'last_visit' not in request.session:
        request.session['last_visit'] = ''

    # request.session['last_visit'] = str(datetime.now() - timedelta(days=1))
    request.session['visits'] += 1

    categories = Category.objects.order_by('-views')
    pages = Page.objects.order_by('-views')
    return render(request, 'rango/index.html',
                  {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
                   'categories': categories[:5],
                   'pages': pages[:5]})


def about(request):
    context = {}
    if 'visits' in request.session.keys():
        context['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context)


def admin(request):
    # return HttpResponse('<p>Models in the Rango application</p> <p>Categories</p> <p>Pages</p>')
    return render(request, 'rango/admin.html')


def page(request):
    return render(request, 'rango/page.html')


def show_category(request, category_name_slug):
    # print('category_name_slug:', category_name_slug)
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Exception as e:
        category = None

    pages = Page.objects.filter(category=category)
    return render(request, 'rango/category.html', {'category': category, 'pages': pages})


def add_category(request):
    # todo: Comment the following if when testing the test_chapter7.py.
    if not request.user.is_authenticated:
        return redirect(reverse('rango:login'))

    form = CategoryForm(request.POST)
    instance = None
    if form.is_valid():
        instance = form.save()

    return render(request, 'rango/add_category.html', {'form': form, 'instance': instance})


def add_page(request, category_name_slug):
    # todo: Comment the following if when testing the test_chapter7.py.
    if not request.user.is_authenticated:
        return redirect(reverse('rango:login'))

    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        return redirect(reverse('rango:index'))

    p = Page.objects.create(category=category)
    form = PageForm(request.POST, instance=p)

    if form.is_valid():
        form.save()

    return render(request, 'rango/add_page.html', {'form': form, 'category_name_slug': category_name_slug})


def userprofile(request):
    return HttpResponse()


def register(request):
    if request.method == 'POST':  # Post submit
        try:
            user_form = UserForm({'username': request.POST['username'], 'password': request.POST['password'],
                                  'email': request.POST['email']})
            user_profile_form = UserProfileForm(
                {'website': request.POST['website'], 'picture': request.POST['picture']})

            if user_form.is_valid() and user_profile_form.is_valid():
                user = user_form.save()
                user.set_password(request.POST['password'])
                user.save()

                user_profile = user_profile_form.save(commit=False)
                user_profile.user = user
                user_profile.save()

            return render(request, 'rango/register.html',
                          {'user_form': user_form, 'userprofile_form': user_profile_form, 'status': 'T'})
        except:

            return render(request, 'rango/register.html', {'status': 'F'})
    else:  # normal visit
        user_form = UserForm()
        user_profile_form = UserProfileForm()
        return render(request, 'rango/register.html',
                      {'user_form': user_form, 'userprofile_form': user_profile_form})


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)

        return redirect(reverse('rango:index'))

    return render(request, 'rango/login.html')


def restricted(request):
    if not request.user.is_authenticated:
        return redirect(reverse('rango:login'))

    return render(request, 'rango/restricted.html')


def logout(request):
    auth.logout(request)
    return redirect(reverse('rango:index'))

rango/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    Rango says hey there partner!
    <a href="/rango/about/">About</a>
</body>
</html>

templates/rango/about.html
{% extends 'rango/base.html' %}
{% block title_block %}About Rango{% endblock %}
{% block content %}
    {% for key, value in request.session.items %}
        {% ifequal 'visits' key %}
            Visits: {{ value }}
        {% endifequal %}
    {% endfor %}

    Rango says here is the about page.<br>
    here is the about page.<br>
    This tutorial has been put together by <br>
    <a href="/rango/">Index</a><br>
    {% load static %} <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title_block %}Add a Category{% endblock %}
{% block content %}
    <h1>Add a Category</h1>

    <form action="/rango/add_category/" method="post">
        {% csrf_token %}
        name: <input type="text" name="name"> <br>
        views: <input type="number" name="views"> <br>
        likes: <input type="number" name="likes"> <br>
        <input type="submit" name="submit" value="Create Category" />
    </form>
    {% if not instance %}
        <strong>Category with this Name already exists.</strong>
    {% endif %}
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% block title_block %}Add a Page{% endblock %}
{% block content %}
    <form action="/rango/category/{{ category_name_slug }}/add_page/" method="post">
        {% csrf_token %}
        title: <input type="text" name="title" />
        url: <input type="text" name="url" />
        views: <input type="number" name="views">

        <input type="submit" name="submit" />
    </form>
{% endblock %}

templates/rango/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>Models in the Rango application</p>
    <a>Categories</a>
    <a>Pages</a>
</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango-{% block title_block %}How to Tango with Django!{% endblock %}</title>
</head>
<body>
    <!-- todo: test tests_chapter7.py need remove if judgement. -->
    {% if request.user.is_authenticated %}
        <a href="{% url 'rango:add_category' %}">Add a New Category</a><br />
    {% endif %}
    <a href="{% url 'rango:about' %}">About</a><br />
    <a href="{% url 'rango:index' %}">Index</a><br />

    <ul>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'rango:logout' %}">Logout</a></li>
            <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
        {% else %}
            <li><a href="{% url 'rango:login' %}">Logout</a></li>
            <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
        {% endif %}
    </ul>

    {% block content %}{% endblock %}
</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% block title_block %}{% if category %}{{ category.name }}{% else %}Unknown Category{% endif %}{% endblock %}
{% block content %}

    {% if request.user.is_authenticated %}
        <a href="/rango/category/{{ category.slug }}/add_page/">Add Page</a>
    {% endif %}

    {% if not category %}
        <p>The specified category does not exist.</p>
    {% endif %}

    {% for page in pages %}
        {% empty %} <strong>No pages currently in category.</strong>
    {% endfor %}

    <h1>Other Frameworks</h1>
    <ul>
        <li><a href="http://bottlepy.org/docs/dev/">Bottle</a></li>
        <li><a href="http://flask.pocoo.org">Flask</a></li>
    </ul>
    <a href="/rango/">index</a>
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% block title_block %}Homepage{% endblock %}
{% block content %}
    <h2>Most Liked Categories</h2>
    <h2>Most Viewed Pages</h2>

    {% if request.user.is_authenticated %}
        <p>Rango says howdy testuser!</p>
    {% else %}
        <p>Rango says hey there partner!</p>
    {% endif %}

    <a href="/rango/about/">About</a><br />

    <li><a href="/rango/category/python/">Python</a></li>
    <li><a href="/rango/category/django/">Django</a></li>
    <li><a href="/rango/category/other-frameworks/">Other Frameworks</a></li>

    {% for category in categories %}
        {% empty %} <strong>There are no categories present.</strong>
    {% endfor %}

    {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% empty %} <strong>There are no pages present.</strong>
    {% endfor %}

    <li><a href="/rango/category/test-category/">Test Category</a></li>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% block title_block %}Login{% endblock %}
{% block content %}
    <h1>Login to Rango</h1>
    <form action="{% url 'rango:login' %}" method="post">
        username: <input type="text" name="username" />
        password: <input type="password" name="password" />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page</title>
</head>
<body>
    <div class="text"><a href="?o=1">Title</a></div>
    <div class="text"><a href="?o=2">Category</a></div>
    <div class="text"><a href="?o=3">Url</a></div>

    <table>
        <tr class="row1"><td class="action-checkbox"><input type="checkbox" name="_selected_action" value="1" class="action-select"></td><th class="field-title"><a href="/admin/rango/page/1/change/">TestPage1</a></th><td class="field-category nowrap">TestCategory</td><td class="field-url">https://www.google.com</td></tr>
    </table>
</body>
</html>

templates/rango/register.html
{% extends 'rango/base.html' %}
{% block title_block %}Register{% endblock %}
{% block content %}
    <h1>Register for Rango</h1>
    Rango says: <strong>register here!</strong>

    <form enctype="multipart/form-data" action="/rango/register/" method="post">
        {% csrf_token %}
        {{ user_form }}
        {{ userprofile_form }}
        <p><label for="id_username">Username:</label> <input type="text" name="username" required id="id_username"></p>
        <p><label for="id_password">Password:</label> <input type="password" name="password" required id="id_password"></p>
        <p><label for="id_email">Email:</label> <input type="text" name="email" required id="id_email"></p>
        <input type="submit" name="submit" value="Register" />
    </form>

    <!-- bad_register -->
    {% ifequal status 'F' %}
        <ul class="errorlist"></ul>
    {% endifequal %}

    <!-- good_register -->
    {% ifequal status 'T' %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="/rango/">Return to the homepage.</a>
    {% endifequal %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% block title_block %}Restricted Page{% endblock %}
{% block content %}

{% endblock %}